export const domains = [
  { domain: ".com" },
  { domain: ".orion" },
  { domain: ".eu" },
  { domain: ".orion" },
  { domain: ".io" },
  { domain: ".gold" },
  { domain: ".silver" },
  { domain: ".ua" },
  { domain: ".us" },
  { domain: ".money" },
  { domain: ".gov" },
  { domain: ".bank" },
  { domain: ".org" },
  { domain: ".net" },
];
